// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 1883435005929017343),
      name: 'UserCredintial',
      lastPropertyId: const IdUid(8, 681332612345323647),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 996277412980353045),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 6366480572496883148),
            name: 'firstName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3036990656861342047),
            name: 'lastName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 6412355937165229247),
            name: 'mobilePhone',
            type: 6,
            flags: 40,
            indexId: const IdUid(1, 1207333499301084878)),
        ModelProperty(
            id: const IdUid(5, 9067485800503200337),
            name: 'country',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 2980629634835532648),
            name: 'city',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 5222654952858578007),
            name: 'area',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 681332612345323647),
            name: 'password',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[
        ModelBacklink(
            name: 'userDetialsProviders',
            srcEntity: 'UserDetailPovider',
            srcField: 'userCredintial')
      ]),
  ModelEntity(
      id: const IdUid(2, 7352852851813603171),
      name: 'UserDetailPovider',
      lastPropertyId: const IdUid(4, 2707190868540657943),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2756989235560911303),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5578121549995201184),
            name: 'profession',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7174325178159447214),
            name: 'yearsOfExperiance',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2707190868540657943),
            name: 'userCredintialId',
            type: 11,
            flags: 520,
            indexId: const IdUid(2, 2898517610738577929),
            relationTarget: 'UserCredintial')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 7352852851813603171),
      lastIndexId: const IdUid(2, 2898517610738577929),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    UserCredintial: EntityDefinition<UserCredintial>(
        model: _entities[0],
        toOneRelations: (UserCredintial object) => [],
        toManyRelations: (UserCredintial object) => {
              RelInfo<UserDetailPovider>.toOneBacklink(
                  4,
                  object.id,
                  (UserDetailPovider srcObject) =>
                      srcObject.userCredintial): object.userDetialsProviders
            },
        getId: (UserCredintial object) => object.id,
        setId: (UserCredintial object, int id) {
          object.id = id;
        },
        objectToFB: (UserCredintial object, fb.Builder fbb) {
          final firstNameOffset = fbb.writeString(object.firstName);
          final lastNameOffset = fbb.writeString(object.lastName);
          final countryOffset = fbb.writeString(object.country);
          final cityOffset = fbb.writeString(object.city);
          final areaOffset = fbb.writeString(object.area);
          final passwordOffset = fbb.writeString(object.password);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, firstNameOffset);
          fbb.addOffset(2, lastNameOffset);
          fbb.addInt64(3, object.mobilePhone);
          fbb.addOffset(4, countryOffset);
          fbb.addOffset(5, cityOffset);
          fbb.addOffset(6, areaOffset);
          fbb.addOffset(7, passwordOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = UserCredintial(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              firstName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              lastName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              country: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              city: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''),
              area: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, ''),
              mobilePhone:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              password: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 18, ''));
          InternalToManyAccess.setRelInfo(
              object.userDetialsProviders,
              store,
              RelInfo<UserDetailPovider>.toOneBacklink(4, object.id,
                  (UserDetailPovider srcObject) => srcObject.userCredintial),
              store.box<UserCredintial>());
          return object;
        }),
    UserDetailPovider: EntityDefinition<UserDetailPovider>(
        model: _entities[1],
        toOneRelations: (UserDetailPovider object) => [object.userCredintial],
        toManyRelations: (UserDetailPovider object) => {},
        getId: (UserDetailPovider object) => object.id,
        setId: (UserDetailPovider object, int id) {
          object.id = id;
        },
        objectToFB: (UserDetailPovider object, fb.Builder fbb) {
          final professionOffset = fbb.writeString(object.profession);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, professionOffset);
          fbb.addInt64(2, object.yearsOfExperiance);
          fbb.addInt64(3, object.userCredintial.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = UserDetailPovider(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              profession: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              yearsOfExperiance:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          object.userCredintial.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.userCredintial.attach(store);
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [UserCredintial] entity fields to define ObjectBox queries.
class UserCredintial_ {
  /// see [UserCredintial.id]
  static final id =
      QueryIntegerProperty<UserCredintial>(_entities[0].properties[0]);

  /// see [UserCredintial.firstName]
  static final firstName =
      QueryStringProperty<UserCredintial>(_entities[0].properties[1]);

  /// see [UserCredintial.lastName]
  static final lastName =
      QueryStringProperty<UserCredintial>(_entities[0].properties[2]);

  /// see [UserCredintial.mobilePhone]
  static final mobilePhone =
      QueryIntegerProperty<UserCredintial>(_entities[0].properties[3]);

  /// see [UserCredintial.country]
  static final country =
      QueryStringProperty<UserCredintial>(_entities[0].properties[4]);

  /// see [UserCredintial.city]
  static final city =
      QueryStringProperty<UserCredintial>(_entities[0].properties[5]);

  /// see [UserCredintial.area]
  static final area =
      QueryStringProperty<UserCredintial>(_entities[0].properties[6]);

  /// see [UserCredintial.password]
  static final password =
      QueryStringProperty<UserCredintial>(_entities[0].properties[7]);
}

/// [UserDetailPovider] entity fields to define ObjectBox queries.
class UserDetailPovider_ {
  /// see [UserDetailPovider.id]
  static final id =
      QueryIntegerProperty<UserDetailPovider>(_entities[1].properties[0]);

  /// see [UserDetailPovider.profession]
  static final profession =
      QueryStringProperty<UserDetailPovider>(_entities[1].properties[1]);

  /// see [UserDetailPovider.yearsOfExperiance]
  static final yearsOfExperiance =
      QueryIntegerProperty<UserDetailPovider>(_entities[1].properties[2]);

  /// see [UserDetailPovider.userCredintial]
  static final userCredintial =
      QueryRelationToOne<UserDetailPovider, UserCredintial>(
          _entities[1].properties[3]);
}
